---
- name: PostgreSQL Installation and Configuration
  hosts: database
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install packages
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-psycopg2
        state: present
    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: /var/lib/postgresql/14/main/pg_hba.conf
      register: postgres_data
    - name: Initialize PostgreSQL
      ansible.builtin.shell: /usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/14/main
      become: true
      become_user: postgres
      when: not postgres_data.stat.exists
    - name: Start and enable service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
    - name: Install PostgreSQL client package
      ansible.builtin.apt:
        name: postgresql-client
        state: present
      changed_when: false
    - name: Create superuser role
      ansible.builtin.command: |
        
        sudo -u postgres createuser --superuser vamshi
      changed_when: false
    - name: Create new database
      ansible.builtin.postgresql_db:
        name: vamshi
        owner: vamshi
        login_user: postgres
        login_password: your_postgres_password
        login_unix_socket: /var/run/postgresql
        state: present
      changed_when: false
    - name: Add system user
      ansible.builtin.user:
        name: vamshi
        state: present
