pipeline {
    agent any {
        
    }
    
    stages {
        stage('checkout') {
            steps {
                git 'https://github.com/vamshikrishna1997/postgresql.git'
            }
        }
        stage('postgresql install and database creation') {
            steps {
                sh 'ansible-playbook -i inventory postgresql.yml'
            }
        }
    }
}            

